### ISSUE TITLE
Change peer dependency from parcel-bundler to just parcel

### ISSUE THREAD

**Issue by denizdogan** [101arrowz/pwa-manifest#10]
When installing this package, NPM will complain about not finding the peer dependency "parcel-bundler", but as I understand it, it should be just "parcel" nowadays.

If you agree, I think it would mean a major semver version update, so it should be in 3.x.

**Comment by 101arrowz** [comment]
Are you referring to Parcel v2? If so, that's a planned update once documentation is written for plugins.  It's a completely new code structure from what I can gather. Actually, I think it needs a different name too (`parcel-runtime-pwa-manifest`) because there are specific types of plugins now. If you want me to release it before the full documentation is released, I'll try my best, but for now there's no v2 support.

**Comment by denizdogan** [comment]
@101arrowz No, I'm talking about v1, it's also available as just "parcel". However, I may have misunderstood which one is the one to use. Some seem to prefer using "parcel" and some think "parcel-bundler" is the right one. It's confusing.

**Comment by 101arrowz** [comment]
I'd strongly suggest using `parcel-bundler`. It's less confusing that way, especially because most of the Parcel documentation [points to that rather than "parcel"](https://parceljs.org/getting_started.html).
